name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/490/downloads/paper-1.20.4-490.jar
    - name: Extract
      run: .\java Xmx16G -jar paper-1.20.4-490.jar nogui\
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Create server
      run: .\java Xmx16G -jar paper-1.20.4-490.jar nogui\
